### ISSUE TITLE
Is it possible to give me all the correct demos?

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/assignment_make-it-roll#3]
May I ask the correct demos? Due to time lag, it seems that we can not communicate in time. So is it possible to give me all the correct demos? When I found errors, firstly, I can correct my codes referring to the correct demos.

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

If you drop me here your email, I'll send you an archive containing the solutions.

**Comment by YANGGANG1971** [comment]
My email is yanggangfeng@ircn.jp. I appreciate your help.

**Comment by pattacini** [comment]
Sent 👍

**Comment by linzdg** [comment]
Recently I learned the tutorials and tried to perform the assignment. May I ask  the solutions about the assignment_make-it-roll and the assignment_grasp-it for reference too? My email is linzdg@163.com.

**Comment by pattacini** [comment]
@linzdg just sent 👍

**Comment by hellovuong** [comment]
Dear Sir,
I am the beginner to iCub and YARP, currently learned the tutorial and tried to do the assignment. Can I ask for the solution of the task assignment_makeit-roll for reference? My email: longvuongkttv@yahoo.com
