### ISSUE TITLE
While executing the assignment of Make_It_Roll, 4 ports cannot connect! 

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/assignment_make-it-roll#5]
The codes were from the solutions that you provide me by email. 
Type the command line as follows.

> yarpserver --write
> yarp check 
> yarpmanager 

Execute the following in order.

1. Assignment_on_Make_It_Roll_System
2. Assignment_on_Make_It_Roll_App_icubSim
3. Assignment_on_Make_It_Roll_App_icub

The errors occurred as follows.
![image](https://user-images.githubusercontent.com/55526431/69505418-326bd100-0f6d-11ea-8e4d-51b73d20df1d.png)

**Comment by pattacini** [comment]
Try out a brand new Gitpod workspace by clicking on https://gitpod.io/#https://github.com/vvv-school/assignment_make-it-roll.

Then:
1. Upload the zip containing the solution.
1. Unzip the archive.
1. Build the source:
     ```sh
     $ cd ${path_to_source}
     $ mkdir -p build && cd build
     $ cmake .. && make install
     ```
1. Launch the server on one console:
    ```sh
    $ yarpserver --write
    ```
1. Excute the commands reported in the [instructions][1].
1. Launch yarpmanager:
    ```sh
    $ yarpmanager
    ```
1. Do the following in a row:
    1. Open and run `Assignment_on_Make_It_Roll_System`.
    1. Open and run `Assignment_on_Make_It_Roll_App`.
    1. Make the connections of the latter app.
    1. Open up a shell and do:
         ```sh
         $ yarp rpc /service
         >> look_down
         >> make_it_roll
         ```

I've gone through all the above steps successfully.

[1]: https://github.com/vvv-school/assignment_make-it-roll#notes
