### ISSUE TITLE
Wrong port names for the right camera

### ISSUE THREAD

**Issue by xEnVrE** [vvv-school/assignment_make-it-roll#9]
After reading https://github.com/robotology/icub-models/issues/195, I noticed that this assignment is making the assumption that the following port exists for the simulated RGB cameras:

```console
cd assignment_make-it-roll
grep -nre "rgbImage:o" .
./smoke-test/fixtures/fixture.xml:57:            <port timeout="10">/icubSim/cam/left/rgbImage:o</port>
./smoke-test/fixtures/fixture.xml:58:            <port timeout="10">/icubSim/cam/right/rgbImage:o</port>
./smoke-test/fixtures/fixture.xml:68:        <from>/icubSim/cam/left/rgbImage:o</from>
./smoke-test/fixtures/fixture.xml:73:        <from>/icubSim/cam/right/rgbImage:o</from>
./app/scripts/assignment_make-it-roll-app-icubSim.xml:7:      <port>/icubSim/cam/left/rgbImage:o</port>
./app/scripts/assignment_make-it-roll-app-icubSim.xml:8:      <port>/icubSim/cam/right/rgbImage:o</port>
./app/scripts/assignment_make-it-roll-app-icubSim.xml:33:      <from>/icubSim/cam/left/rgbImage:o</from>
./app/scripts/assignment_make-it-roll-app-icubSim.xml:39:      <from>icubSim/cam/left/rgbImage:o</from>
```
namely, `/icubSim/cam/left/rgbImage:o` and `/icubSim/cam/left/rgbImage:o`. However, the simulated model exposes different names, i.e. `/icubSim/cam/left/rgbImage:o` and `/icubSim/cam/right`, due to https://github.com/robotology/icub-models/issues/44#issuecomment-664225199.

Should we fix the wrong name?

Thanks

**Comment by traversaro** [comment]
fyi @davidegorbani

**Comment by traversaro** [comment]
x-link to relevant issue: https://github.com/robotology/icub-models/issues/47 .

**Comment by davidegorbani** [comment]
In the `assignment_make-it-roll-app-icubSim.xml` file I changed the port `/icubSim/cam/right/rgbImage:o` with `/icubSim/cam/right/` and now the two `yarpviewer` show the images of the cameras.

**Comment by pattacini** [comment]
We definitely need to fix the wrong names, but:
- I ought to understand how the module has been keeping working till now 😄 
- I would appreciate making only one fix here[^1], hence solving https://github.com/robotology/icub-models/issues/47 first.

[^1]: I will need to update many other gazebo-based apps too.

**Comment by xEnVrE** [comment]
> I would appreciate making only one fix here, hence solving https://github.com/robotology/icub-models/issues/47

Totally agree with you.

**Comment by pattacini** [comment]
The assignment was working just fine when @martinaxgloria completed it this year.
This means that the port of the right camera was opened with the correct name.

We need to investigate what happened in the meantime.
Maybe, something to do with the distro 2023.02.0?

**Comment by pattacini** [comment]
Somehow, this change might have been removed:
- https://github.com/robotology/icub-models/pull/45/files

**Comment by pattacini** [comment]
With @xEnVrE, we agreed to reinstate the customization to have left and right camera port names equal.
Later, we will harmonize the names to make them equal to those on the physical robot.

**Comment by pattacini** [comment]
Fix proposed via https://github.com/robotology/icub-models/pull/196.
Closing.

**Comment by pattacini** [comment]
Re-tested after [Distro 2023.02.2](https://github.com/orgs/robotology/discussions/613#discussioncomment-5545214) and everything worked as expected.

cc @xEnVrE @davidegorbani
